### ISSUE TITLE
output

### ISSUE THREAD

**Issue by yudadabing** [v1t0ry/Nonlinear-Unsharp-Masking#2]
i just input the '02_ori.png',however ,the output is different from the result in paper.

**Comment by junpan19** [comment]
I also meet this problem that the color of my result has been changed compared to the input image.

**Comment by datngo93** [comment]
Thank you for your comments~~

I have checked the source code and found that it missed a line for converting the input data from [0, 1] domain to [-1, 1] domain.

I have added a line "x=2*x-1" and the result is now identical to that in the paper.

If you experience any problems, please let me know!
